/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppViolationsIndexRouteImport } from './routes/_app.violations.index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppMedicalIndexRouteImport } from './routes/_app.medical.index'
import { Route as AppLeaveRequestsIndexRouteImport } from './routes/_app.leave-requests.index'
import { Route as AppDelaysIndexRouteImport } from './routes/_app.delays.index'
import { Route as AppViolationsNewRouteImport } from './routes/_app.violations.new'
import { Route as AppStudentsNewRouteImport } from './routes/_app.students.new'
import { Route as AppMedicalNewRouteImport } from './routes/_app.medical.new'
import { Route as AppLeaveRequestsNewRouteImport } from './routes/_app.leave-requests.new'
import { Route as AppDelaysNewRouteImport } from './routes/_app.delays.new'
import { Route as AppStudentsIdIndexRouteImport } from './routes/_app.students.$id.index'
import { Route as AppStudentsIdEditRouteImport } from './routes/_app.students.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppViolationsIndexRoute = AppViolationsIndexRouteImport.update({
  id: '/violations/',
  path: '/violations/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalIndexRoute = AppMedicalIndexRouteImport.update({
  id: '/medical/',
  path: '/medical/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsIndexRoute = AppLeaveRequestsIndexRouteImport.update({
  id: '/leave-requests/',
  path: '/leave-requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppDelaysIndexRoute = AppDelaysIndexRouteImport.update({
  id: '/delays/',
  path: '/delays/',
  getParentRoute: () => AppRoute,
} as any)
const AppViolationsNewRoute = AppViolationsNewRouteImport.update({
  id: '/violations/new',
  path: '/violations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalNewRoute = AppMedicalNewRouteImport.update({
  id: '/medical/new',
  path: '/medical/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsNewRoute = AppLeaveRequestsNewRouteImport.update({
  id: '/leave-requests/new',
  path: '/leave-requests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDelaysNewRoute = AppDelaysNewRouteImport.update({
  id: '/delays/new',
  path: '/delays/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdIndexRoute = AppStudentsIdIndexRouteImport.update({
  id: '/students/$id/',
  path: '/students/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdEditRoute = AppStudentsIdEditRouteImport.update({
  id: '/students/$id/edit',
  path: '/students/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/feedback': typeof AppFeedbackRoute
  '/delays/new': typeof AppDelaysNewRoute
  '/leave-requests/new': typeof AppLeaveRequestsNewRoute
  '/medical/new': typeof AppMedicalNewRoute
  '/students/new': typeof AppStudentsNewRoute
  '/violations/new': typeof AppViolationsNewRoute
  '/delays/': typeof AppDelaysIndexRoute
  '/leave-requests/': typeof AppLeaveRequestsIndexRoute
  '/medical/': typeof AppMedicalIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/violations/': typeof AppViolationsIndexRoute
  '/students/$id/edit': typeof AppStudentsIdEditRoute
  '/students/$id/': typeof AppStudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/feedback': typeof AppFeedbackRoute
  '/': typeof AppIndexRoute
  '/delays/new': typeof AppDelaysNewRoute
  '/leave-requests/new': typeof AppLeaveRequestsNewRoute
  '/medical/new': typeof AppMedicalNewRoute
  '/students/new': typeof AppStudentsNewRoute
  '/violations/new': typeof AppViolationsNewRoute
  '/delays': typeof AppDelaysIndexRoute
  '/leave-requests': typeof AppLeaveRequestsIndexRoute
  '/medical': typeof AppMedicalIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/violations': typeof AppViolationsIndexRoute
  '/students/$id/edit': typeof AppStudentsIdEditRoute
  '/students/$id': typeof AppStudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/delays/new': typeof AppDelaysNewRoute
  '/_app/leave-requests/new': typeof AppLeaveRequestsNewRoute
  '/_app/medical/new': typeof AppMedicalNewRoute
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/violations/new': typeof AppViolationsNewRoute
  '/_app/delays/': typeof AppDelaysIndexRoute
  '/_app/leave-requests/': typeof AppLeaveRequestsIndexRoute
  '/_app/medical/': typeof AppMedicalIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/violations/': typeof AppViolationsIndexRoute
  '/_app/students/$id/edit': typeof AppStudentsIdEditRoute
  '/_app/students/$id/': typeof AppStudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/feedback'
    | '/delays/new'
    | '/leave-requests/new'
    | '/medical/new'
    | '/students/new'
    | '/violations/new'
    | '/delays/'
    | '/leave-requests/'
    | '/medical/'
    | '/students/'
    | '/violations/'
    | '/students/$id/edit'
    | '/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/feedback'
    | '/'
    | '/delays/new'
    | '/leave-requests/new'
    | '/medical/new'
    | '/students/new'
    | '/violations/new'
    | '/delays'
    | '/leave-requests'
    | '/medical'
    | '/students'
    | '/violations'
    | '/students/$id/edit'
    | '/students/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/feedback'
    | '/_app/'
    | '/_app/delays/new'
    | '/_app/leave-requests/new'
    | '/_app/medical/new'
    | '/_app/students/new'
    | '/_app/violations/new'
    | '/_app/delays/'
    | '/_app/leave-requests/'
    | '/_app/medical/'
    | '/_app/students/'
    | '/_app/violations/'
    | '/_app/students/$id/edit'
    | '/_app/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/violations/': {
      id: '/_app/violations/'
      path: '/violations'
      fullPath: '/violations/'
      preLoaderRoute: typeof AppViolationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical/': {
      id: '/_app/medical/'
      path: '/medical'
      fullPath: '/medical/'
      preLoaderRoute: typeof AppMedicalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests/': {
      id: '/_app/leave-requests/'
      path: '/leave-requests'
      fullPath: '/leave-requests/'
      preLoaderRoute: typeof AppLeaveRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delays/': {
      id: '/_app/delays/'
      path: '/delays'
      fullPath: '/delays/'
      preLoaderRoute: typeof AppDelaysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/violations/new': {
      id: '/_app/violations/new'
      path: '/violations/new'
      fullPath: '/violations/new'
      preLoaderRoute: typeof AppViolationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical/new': {
      id: '/_app/medical/new'
      path: '/medical/new'
      fullPath: '/medical/new'
      preLoaderRoute: typeof AppMedicalNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests/new': {
      id: '/_app/leave-requests/new'
      path: '/leave-requests/new'
      fullPath: '/leave-requests/new'
      preLoaderRoute: typeof AppLeaveRequestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delays/new': {
      id: '/_app/delays/new'
      path: '/delays/new'
      fullPath: '/delays/new'
      preLoaderRoute: typeof AppDelaysNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id/': {
      id: '/_app/students/$id/'
      path: '/students/$id'
      fullPath: '/students/$id/'
      preLoaderRoute: typeof AppStudentsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id/edit': {
      id: '/_app/students/$id/edit'
      path: '/students/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AppStudentsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDelaysNewRoute: typeof AppDelaysNewRoute
  AppLeaveRequestsNewRoute: typeof AppLeaveRequestsNewRoute
  AppMedicalNewRoute: typeof AppMedicalNewRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppViolationsNewRoute: typeof AppViolationsNewRoute
  AppDelaysIndexRoute: typeof AppDelaysIndexRoute
  AppLeaveRequestsIndexRoute: typeof AppLeaveRequestsIndexRoute
  AppMedicalIndexRoute: typeof AppMedicalIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppViolationsIndexRoute: typeof AppViolationsIndexRoute
  AppStudentsIdEditRoute: typeof AppStudentsIdEditRoute
  AppStudentsIdIndexRoute: typeof AppStudentsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppIndexRoute: AppIndexRoute,
  AppDelaysNewRoute: AppDelaysNewRoute,
  AppLeaveRequestsNewRoute: AppLeaveRequestsNewRoute,
  AppMedicalNewRoute: AppMedicalNewRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppViolationsNewRoute: AppViolationsNewRoute,
  AppDelaysIndexRoute: AppDelaysIndexRoute,
  AppLeaveRequestsIndexRoute: AppLeaveRequestsIndexRoute,
  AppMedicalIndexRoute: AppMedicalIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppViolationsIndexRoute: AppViolationsIndexRoute,
  AppStudentsIdEditRoute: AppStudentsIdEditRoute,
  AppStudentsIdIndexRoute: AppStudentsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
